import React from 'react';
import {
  Server,
  Layout,
  Database,
  Cpu,
  Terminal,
  Code,
  FileCode,
  Binary,
  Layers,
  ShoppingBag,
  Network,
  Palette,
  Sparkles,
  Columns,
  Boxes,
  HardDrive,
  FolderGit2,
  GitBranch,
  Github,
  FolderTree,
  CheckSquare,
  Brain,
  Zap,
  Search,
  MessageSquareCode,
  ShieldCheck,
  Bot,
  Workflow,
  ExternalLink,
  Calendar,
  MapPin,
  Mail,
  Phone,
  Linkedin,
  ArrowRight,
  Download,
  GraduationCap,
  Award,
  CheckCircle2,
  AlertCircle,
  Copy,
  Check,
  Menu,
  X,
  ChevronRight,
  Sparkle,
} from 'lucide-react';

interface DynamicIconProps {
  name: string;
  className?: string;
}

export const DynamicIcon: React.FC<DynamicIconProps> = ({ name, className = 'w-5 h-5' }) => {
  const iconsMap: Record<string, React.ElementType> = {
    Server,
    Layout,
    Database,
    Cpu,
    Terminal,
    Code,
    FileCode,
    Binary,
    Layers,
    ShoppingBag,
    Network,
    Palette,
    Sparkles,
    Columns,
    Boxes,
    HardDrive,
    FolderGit2,
    GitBranch,
    Github,
    FolderTree,
    CheckSquare,
    Brain,
    Zap,
    Search,
    MessageSquareCode,
    ShieldCheck,
    Bot,
    Workflow,
    ExternalLink,
    Calendar,
    MapPin,
    Mail,
    Phone,
    Linkedin,
    ArrowRight,
    Download,
    GraduationCap,
    Award,
    CheckCircle2,
    AlertCircle,
    Copy,
    Check,
    Menu,
    X,
    ChevronRight,
    Sparkle,
  };

  const Component = iconsMap[name] || Terminal;
  return <Component className={className} />;
};
